language: node_js
sudo: false

node_js:
  - 9

script:
  - yarn build
  - yarn lint

after_success:
  # add a deploy key to use automatic github pages deployment
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    yarn deploy;
    fi
